### ISSUE TITLE
[Medium] Fix dev env

### ISSUE THREAD

**Issue by Flaque** [gu-app-club/portfolio#3]
At the moment, the development environment isn't loading in all the CSS all the time, which leads to weird issues any time you refresh the page.

**Comment by maxchehab** [comment]
What is the difference between running the development environment and the production environment?
What are the commands to start either?

**Comment by Flaque** [comment]
Production builds the entire page at once. Dev rebuilds in chunks to help support hot-code reloading.

**Comment by Flaque** [comment]
Solved via: fe22bdd6095b3613efa9483e723fbc03d4f7b3ba

A+ Max <3
