### ISSUE TITLE
[Medium] Create an API endpoint that makes a new access code and adds it to the DB 

### ISSUE THREAD

**Issue by Flaque** [gu-app-club/portfolio#6]
We'd like to provide GU students with access codes (so we can limit registration only to GU students). 

We should have an API request like:
``` 
POST localhost:8080/access/new
```

That creates a new one, adds it to the DB and returns it to the user. 

## Non-Goals
No authentication is required for this completion yet, we can handle that later.

**Comment by maxchehab** [comment]
https://github.com/gu-app-club/portfolio/blob/master/backend/README.md#create-accesscode-get
